// Type definition for channels
export interface IPTVChannel {
  name: string
  url: string
  logo?: string
  category?: string
}

/**
 * Converts any YouTube URL into an embeddable format that always works
 */
function normalizeYouTubeUrl(url: string): string {
  if (!url.includes("youtube") && !url.includes("youtu.be")) return url

  try {
    const u = new URL(url)

    if (u.hostname === "youtu.be") {
      const id = u.pathname.replace("/", "")
      return `https://www.youtube-nocookie.com/embed/${id}`
    }

    if (u.searchParams.has("v")) {
      const id = u.searchParams.get("v")
      return `https://www.youtube-nocookie.com/embed/${id}`
    }

    if (u.pathname.startsWith("/live/")) {
      const id = u.pathname.split("/live/")[1]
      return `https://www.youtube-nocookie.com/embed/${id}?autoplay=1`
    }

    if (u.pathname.includes("/embed/")) {
      return url.replace("youtube.com", "youtube-nocookie.com")
    }

    return url
  } catch {
    return url
  }
}

const channelsByCountry: Record<string, IPTVChannel[]> = {
  Afghanistan: [
    { name: "Tolo News", url: "https://example.com/tolo.m3u8", category: "News", logo: "https://i.imgur.com/tolo.png" },
    { name: "Ariana TV", url: "https://example.com/ariana.m3u8", category: "Entertainment", logo: "https://i.imgur.com/ariana.png" },
  ],
  
  Andorra: [
    {
      name: "RTVA Andorra",
      url: "https://livesg1.rtva.hiway.media/aa2d69af-76a0-4077-a57e-0445c4061f86/manifest.m3u8",
      category: "General",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Rtva_logo.svg/320px-Rtva_logo.svg.png",
    },
    {
      name: "Lòria TV",
      url: "https://www.youtube-nocookie.com/embed/QN6UquUpjCk",
      category: "Local",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Coat_of_arms_of_La_Massana.svg/320px-Coat_of_arms_of_La_Massana.svg.png",
    },
  ],
  Italy: [
    { name: "7 RadioVisione", url: "https://stream10.xdevel.com/video1s976543-1932/stream/playlist.m3u8" },
    { name: "7 STORIA", url: "https://stream10.xdevel.com/video2s976543-2104/stream/playlist.m3u8" },
    { name: "7 YOU & ME", url: "https://stream10.xdevel.com/video0s977798-2239/stream/playlist.m3u8" },
    { name: "12 TV Parma", url: "https://5929b138b139d.streamlock.net/12TVParma/livestream/playlist.m3u8" },
    { name: "51 Radio TV", url: "https://59d7d6f47d7fc.streamlock.net/canale51/canale51/playlist.m3u8" },
    { name: "70-80 TV (1080P)", url: "https://585b674743bbb.streamlock.net/9050/9050/playlist.m3u8" },
    { name: "111 TV", url: "https://5db313b643fd8.streamlock.net/111/111/playlist.m3u8" },
    { name: "A2i TV", url: "https://stream.sen-gt.com/A2itv/myStream/playlist.m3u8" },
    { name: "ACI Sport TV", url: "https://webstream.multistream.it/memfs/e2cb3629-c1a2-495b-b43a-9eb386f04ed8.m3u8" },
    { name: "Adnkronos", url: "https://5e73cf528f404.streamlock.net/GR_sport/livestream/playlist.m3u8" },
    { name: "Alto Adige TV", url: "https://5f204aff97bee.streamlock.net/AltoAdigeTV/livestream/playlist.m3u8" },
    { name: "Antenna 2 TV", url: "https://58f12ffd2447a.streamlock.net/Antenna2/livestream/playlist.m3u8" },
    { name: "Aurora Arte", url: "https://59d7d6f47d7fc.streamlock.net/auroraarte/auroraarte/playlist.m3u8" },
    { name: "Azzurra TV", url: "https://ed05.top-ix.org/avtvlive/azzurra/streaming/playlist.m3u8" },
    { name: "BBC Drama Italy", url: "https://amg00793-amg00793c41-rakuten-it-5445.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "BBC Top Gear Italy", url: "https://amg00793-amg00793c43-rakuten-it-5537.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "BeJoy.kids", url: "https://64b16f23efbee.streamlock.net/bejoy/bejoy/playlist.m3u8" },
    { name: "Bergamo TV", url: "https://db142859fd5541b09de25d6507f1f2d3.msvdn.net/live/S17501676/oIxAsgEEA46M/playlist_dvr.m3u8" },
    { name: "Bom Channel", url: "https://5f22d76e220e1.streamlock.net/canale6/canale6/playlist.m3u8" },
    { name: "CafeTV24", url: "https://srvx1.selftv.video/cafe/live/playlist.m3u8" },
    { name: "Calabria TV", url: "https://64b16f23efbee.streamlock.net/calabriatv/calabriatv/playlist.m3u8" },
    { name: "Camera dei Deputati (via RR)", url: "https://video-ar.radioradicale.it/diretta/camera2/playlist.m3u8" },
    { name: "Canale 2 Altamura", url: "https://59d7d6f47d7fc.streamlock.net/canale2/canale2/playlist.m3u8" },
    { name: "Canale 21 Extra", url: "https://0ff9dd7fe9b64bc08a5fc4ed525454c3.msvdn.net/live/S42170132/sT6C3LFaD1iA/playlist.m3u8" },
    { name: "CarinaTV", url: "https://samson.streamerr.co:8081/carinatv/tracks-v1a1/playlist.m3u8" },
    { name: "Company TV", url: "https://5929b138b139d.streamlock.net/CompanyTV/smil:CompanyTV.smil/master.m3u8" },
    { name: "Deejay TV", url: "https://4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S85984808/sMO0tz9Sr2Rk/playlist.m3u8" },
    { name: "DI.TV 80", url: "https://5f22d76e220e1.streamlock.net/ditv80/ditv80/playlist.m3u8" },
    { name: "Elive TV Brescia", url: "https://59d7d6f47d7fc.streamlock.net/elivebresciatv/elivebresciatv/playlist.m3u8" },
    { name: "Entella TV", url: "https://5f22d76e220e1.streamlock.net/EntellaTV/EntellaTV/playlist.m3u8" },
    { name: "Esperia TV", url: "https://59d7d6f47d7fc.streamlock.net/esperiatv/esperiatv/playlist.m3u8" },
    { name: "Etna Espresso Channel", url: "https://5db313b643fd8.streamlock.net/Etnachannelponte/Etnachannelponte/playlist.m3u8" },
    { name: "èTv Marche", url: "https://live.ipstream.it/etvmarche/etvmarche.stream/playlist.m3u8" },
    { name: "èTv Rete 7", url: "https://live.ipstream.it/etv/etv.stream/playlist.m3u8" },
    { name: "Euro TV", url: "https://5f22d76e220e1.streamlock.net/eurotv/eurotv/playlist.m3u8" },
    { name: "FM ITALIA", url: "https://stream2.xdevel.com/video0s975817-1183/stream/playlist.m3u8" },
    { name: "Giornale Radio TV", url: "https://5f204aff97bee.streamlock.net/GR_tv/livestream/playlist.m3u8" },
    { name: "Giovanni Paolo TV", url: "https://media2021.rtvweb.com/giovannipaolotv/web/playlist.m3u8" },
    { name: "GO-TV Canale 163", url: "https://6zklxkbbdw9b-hls-live.mariatvcdn.it/msmotor/2f759512164fc6fe4acbed6a5648993a.sdp/playlist.m3u8" },
    { name: "Gold TV", url: "https://streaming.softwarecreation.it/GoldTv/GoldTv/playlist.m3u8" },
    { name: "Gold TV Sat", url: "https://streaming.softwarecreation.it/GoldTvSat/GoldTvSat/playlist.m3u8" },
    { name: "GRP VERATV", url: "https://webstream.multistream.it/memfs/a3195c96-f884-4c74-924f-2648814fc0b5_output_0.m3u8" },
    { name: "Hell's Kitchen Italy", url: "https://amg00654-itv-amg00654c20-rakuten-it-3615.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "Horse TV", url: "https://a-cdn.klowdtv.com/live2/horsetv_720p/playlist.m3u8" },
    { name: "Icaro TV", url: "https://59d7d6f47d7fc.streamlock.net/icarotv/icarotv/playlist.m3u8" },
    { name: "INWILD", url: "https://amg00861-amg00861c7-firetv-us-4725.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "Italia 2", url: "https://59d7d6f47d7fc.streamlock.net/italia2/italia2/playlist.m3u8" },
    { name: "Italia 7", url: "https://streaming.softwarecreation.it/Italia7/Italia7/playlist.m3u8" },
    { name: "Italia Channel", url: "https://stream1.aswifi.it/italiachannel/stream/index.m3u8" },
    { name: "Italian Fishing TV", url: "https://fms.premio.link/fishingtv/playlist.m3u8" },
    { name: "ItalianFishingTV", url: "https://www.youtube-nocookie.com/embed/AmU87ZNHOI8" },
    { name: "Iunior TV", url: "https://5f22d76e220e1.streamlock.net/iuniortv/iuniortv/chunklist_w774879328.m3u8" },
    { name: "Iunior TV", url: "https://5f22d76e220e1.streamlock.net/iuniortv/iuniortv/playlist.m3u8" },
    { name: "Juwelo Italia", url: "https://sdn-global-live-streaming-packager-cache.3qsdn.com/7841/7841_264_live.m3u8" },
    { name: "Kiss Kiss Napoli TV", url: "https://58f12ffd2447a.streamlock.net/KKTVNapoli/livestream/playlist.m3u8" },
    { name: "Kiss Kiss TV", url: "https://58f12ffd2447a.streamlock.net/KKMulti/livestream/playlist.m3u8" },
    { name: "La C TV", url: "https://f5842579ff984c1c98d63b8d789673eb.msvdn.net/live/S47282891/JWjL3xqPf4bX/playlist.m3u8" },
    { name: "La TR3 Marsala", url: "https://tsw.streamingwebtv24.it:1936/eslife1/eslife1/playlist.m3u8" },
    { name: "LaC News 24", url: "https://f5842579ff984c1c98d63b8d789673eb.msvdn.net/live/S27391994/HVvPMzy/playlist.m3u8" },
    { name: "Lazio TV", url: "https://streaming.softwarecreation.it/LazioTv/LazioTv/playlist.m3u8" },
    { name: "Lira TV", url: "https://a928c0678d284da5b383f29ecc5dfeec.msvdn.net/live/S57315730/8kTBWibNteJA/playlist.m3u8" },
    { name: "Luna TV", url: "https://5f22d76e220e1.streamlock.net/lunatv/lunatv/playlist.m3u8" },
    { name: "m2o TV", url: "https://4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S62628868/uhdWBlkC1AoO/playlist.m3u8" },
    { name: "MadeinBO TV", url: "https://srvx1.selftv.video/dmchannel/live/playlist.m3u8" },
    { name: "Maria Vision", url: "https://1601580044.rsc.cdn77.org/live/_jcn_/amlst:CHANNEL_2/playlist.m3u8" },
    { name: "Medjugorje Italia TV", url: "https://5f22d76e220e1.streamlock.net/medjugorjeitaliatv/medjugorjeitaliatv/playlist.m3u8" },
    { name: "Minformo TV", url: "https://5db313b643fd8.streamlock.net/MinformoTV/MinformoTV/playlist.m3u8" },
    { name: "Mr. Bean Anime Italy", url: "https://amg00627-amg00627c29-rakuten-it-3989.playouts.now.amagi.tv/playlist/amg00627-banijayfast-mrbeanitcc-rakutenit/playlist.m3u8" },
    { name: "Nuova TV 1", url: "https://nuovatv.net:8443/tv/stream.m3u8" },
    { name: "Odeon 24", url: "https://streaming.softwarecreation.it/Odeon/Odeon/playlist.m3u8" },
    { name: "Onda Novara TV", url: "https://585b674743bbb.streamlock.net/9006/9006/master.m3u8" },
    { name: "Onda TV", url: "https://5926fc9c7c5b2.streamlock.net/9040/9040/chunklist_w1373908906.m3u8" },
    { name: "Orler TV", url: "https://w1.mediastreaming.it/orlertv/livestream/playlist.m3u8" },
    { name: "Paci Contemporary Channel", url: "https://5f22d76e220e1.streamlock.net/pacicontemporarychannel/pacicontemporarychannel/playlist.m3u8" },
    { name: "Parole di Vita", url: "https://64b16f23efbee.streamlock.net/paroledivita/paroledivita/playlist.m3u8" },
    { name: "Peer TV Alto Adige", url: "https://iptv.peer.biz/live/peertv-it.m3u8" },
    { name: "Peer TV South Tyrol", url: "https://iptv.peer.biz/live/peertv-en.m3u8" },
    { name: "Peer TV Südtirol", url: "https://iptv.peer.biz/live/peertv.m3u8" },
    { name: "Prima Free", url: "https://5f22d76e220e1.streamlock.net/primafree/primafree/playlist.m3u8" },
    { name: "Prima TV Sicilia", url: "https://5db313b643fd8.streamlock.net/PrimaTV/PrimaTV/playlist.m3u8" },
    { name: "PrimAntenna TV", url: "https://5f22d76e220e1.streamlock.net/primantenna14/primantenna14/playlist.m3u8" },
    { name: "Primocanale", url: "https://msh0203.stream.seeweb.it/live/flv:stream2.sdp/playlist.m3u8" },
    { name: "Promovideo TV", url: "https://media2021.rtvweb.com/promovideo_web/promovideo/playlist.m3u8" },
    { name: "QSVS: Milanow", url: "https://www.youtube-nocookie.com/embed/PGe4Y5ZWxYE" },
    { name: "QSVS: Top Calcio 24", url: "https://www.youtube-nocookie.com/embed/Nu2JGd0TJaM" },
    { name: "Quarto Canale Flegreo", url: "https://live.mariatvcdn.com/dialogos/171e41deedf405f10c7dd6311387fb43.sdp/playlist.m3u8" },
    { name: "QVC Italia", url: "https://qrg.akamaized.net/hls/live/2017383/lsqvc1it/master.m3u8" },
    { name: "Radio Birikina TV", url: "https://56b50ada2d659.streamlock.net/RadioBirikinaTV/livestream/playlist.m3u8" },
    { name: "Radio Brianza TV", url: "https://57068da1deb21.streamlock.net/radiorbs/radiorbs/playlist.m3u8" },
    { name: "Radio Freccia TV", url: "https://streamcdnb1-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/playlist_video.m3u8" },
  ],
  "United States": [
{ name: "23 ABC Bakersfield CA (KERO)", url: "https://content.uplynk.com/channel/ff809e6d9ec34109abfb333f0d4444b5.m3u8" },
    { name: "30A Darcizzle Offshore", url: "https://30a-tv.com/darcizzle.m3u8" },
    { name: "30A Georgia Hollywood Review TV", url: "https://30a-tv.com/gh.m3u8" },
    { name: "30A Golf Kingdom", url: "https://30a-tv.com/feeds/vidaa/golf.m3u8" },
    { name: "30A Investment Pitch", url: "https://30a-tv.com/feeds/xodglobal/30atv.m3u8" },
    { name: "30A Loomered TV", url: "https://30a-tv.com/loomer.m3u8" },
    { name: "30A Luxe Life Discovered", url: "https://30a-tv.com/feeds/vidaa/luxelife.m3u8" },
    { name: "30A Music", url: "https://30a-tv.com/music.m3u8" },
    { name: "30A Ridiculous TV", url: "https://30a-tv.com/feeds/720p/63.m3u8" },
    { name: "30A Sidewalks", url: "https://30a-tv.com/sidewalks.m3u8" },
    { name: "30A TV Classic Movies", url: "https://30a-tv.com/feeds/pzaz/30atvmovies.m3u8" },
    { name: "30A Television Channel", url: "https://30a-tv.com/feeds/masters/30atv.m3u8" },
    { name: "30A The Beach Show", url: "https://30a-tv.com/beachy.m3u8" },
    { name: "30A We Love Cars", url: "https://30a-tv.com/feeds/vidaa/cars.m3u8" },
    { name: "3ABN Canada", url: "https://3abn.bozztv.com/3abncanada/3ABN/master.m3u8" },
    { name: "3ABN Dare To Dream Network", url: "https://3abn.bozztv.com/3abn2/d2d_live/smil:d2d_live.smil/playlist.m3u8" },
    { name: "3ABN English", url: "https://3abn.bozztv.com/3abn2/3abn_live/smil:3abn_live.smil/playlist.m3u8" },
    { name: "3ABN French", url: "https://3abn.bozztv.com/3abn2/Fre_live/smil:Fre_live.smil/playlist.m3u8" },
    { name: "3ABN International", url: "https://3abn.bozztv.com/3abn2/Int_live/smil:Int_live.smil/playlist.m3u8" },
    { name: "3ABN Kids", url: "https://3abn.bozztv.com/3abn2/Kids_live/smil:Kids_live.smil/playlist.m3u8" },
    { name: "3ABN Latino", url: "https://3abn.bozztv.com/3abn2/Lat_live/smil:Lat_live.smil/playlist.m3u8" },
    { name: "3ABN Praise Him Music Network", url: "https://3abn.bozztv.com/3abn1/PraiseHim/smil:PraiseHim.smil/playlist.m3u8" },
    { name: "3ABN Proclaim! Network", url: "https://3abn.bozztv.com/3abn2/Pro_live/smil:Pro_live.smil/playlist.m3u8" },
    { name: "AABC TV", url: "https://streamer1.connectto.com/AABC_WEB_1201/index.m3u8" },
    { name: "ABC 10 San Diego CA (KGTV)", url: "https://livetv-fa.tubi.video/kgtv2/playlist.m3u8" },
    { name: "ABC 12 Milwaukee WI (WISN)", url: "https://livetv-fa.tubi.video/wisn/playlist.m3u8" },
    { name: "ABC 13 Las Vegas NV (KTNV)", url: "https://content.uplynk.com/channel/39919d3f7a074eefa8bf579214e952f9.m3u8" },
    { name: "ABC 15 Phoenix AZ (KNXV-TV)", url: "https://content.uplynk.com/channel/9deaf22aaa33461f9cac22e030ed00ec.m3u8" },
    { name: "ABC 16 Jackson MS (WAPT)", url: "https://livetv-fa.tubi.video/wapt/playlist.m3u8" },
    { name: "ABC 2 Baltimore MD (WMAR)", url: "https://livetv-fa.tubi.video/wmar/playlist.m3u8" },
    { name: "ABC 22 Savannah GA (WJCL)", url: "https://livetv-fa.tubi.video/wjcl/playlist.m3u8" },
    { name: "ABC 25 Waco TX (KXXV)", url: "https://livetv-fa.tubi.video/kxxv/playlist.m3u8" },
    { name: "ABC 25 West Palm Beach FL (WPBF)", url: "https://livetv-fa.tubi.video/wpbf/playlist.m3u8" },
    { name: "ABC 28 Tampa Bay FL (WFTS)", url: "https://livetv-fa.tubi.video/wfts2/playlist.m3u8" },
    { name: "ABC 3 Lafayette LA (KATC)", url: "https://livetv-fa.tubi.video/katc/playlist.m3u8" },
    { name: "ABC 30 Fresno and Central Valley News (KFSN-DT1)", url: "https://content.uplynk.com/channel/ext/96195dc445894d079a91958abba8d3af/kfsn_24x7_news.m3u8" },
    { name: "ABC 4 Pittsburg PA (WTAE)", url: "https://livetv-fa.tubi.video/wtae/playlist.m3u8" },
    { name: "ABC 40/29 Fort Smith AR (KHBS)", url: "https://livetv-fa.tubi.video/khbs/playlist.m3u8" },
    { name: "ABC 5 Boston MA (WCVB)", url: "https://livetv-fa.tubi.video/wcvb/playlist.m3u8" },
    { name: "ABC 5 Cleveland OH (WEWS)", url: "https://livetv-fa.tubi.video/wews2/playlist.m3u8" },
    { name: "ABC 5 Oklahoma City OK (KOCO)", url: "https://livetv-fa.tubi.video/koco/playlist.m3u8" },
    { name: "ABC 6 Boise ID (KIVI)", url: "https://livetv-fa.tubi.video/kivi/playlist.m3u8" },
    { name: "ABC 6 Indianapolis IN (WRTV)", url: "https://livetv-fa.tubi.video/wrtv/playlist.m3u8" },
    { name: "ABC 7 Albuquerque NM (KOAT)", url: "https://livetv-fa.tubi.video/koat/playlist.m3u8" },
    { name: "ABC 7 Bay Area and San Francisco News (KGO-DT1)", url: "https://content.uplynk.com/channel/ext/4413701bf5a1488db55b767f8ae9d4fa/kgo_24x7_news.m3u8" },
    { name: "ABC 7 Buffalo NY (WKBW)", url: "https://livetv-fa.tubi.video/wkbw/playlist.m3u8" },
    { name: "ABC 7 Denver CO (KMGH)", url: "https://content.uplynk.com/channel/64ca339f04964a5e961c3207a7771bf1.m3u8" },
    { name: "ABC 7 Detroit MI (WXYZ)", url: "https://livetv-fa.tubi.video/wxyz2/playlist.m3u8" },
    { name: "ABC 7 Los Angeles CA (KABC-TV)", url: "https://content.uplynk.com/channel/ext/2118d9222a87420ab69223af9cfa0a0f/kabc_24x7_news.m3u8" },
    { name: "ABC 7 Omaha NE (KETV)", url: "https://livetv-fa.tubi.video/ketv/playlist.m3u8" },
    { name: "ABC 8 Portland ME (WMTW)", url: "https://livetv-fa.tubi.video/wmtw/playlist.m3u8" },
    { name: "ABC 9 Cincinnati OH (WCPO)", url: "https://livetv-fa.tubi.video/wcpo/playlist.m3u8" },
    { name: "ABC 9 Manchester NH (WMUR-TV)", url: "https://livetv-fa.tubi.video/wmur/playlist.m3u8" },
    { name: "ABC 9 Orlando FL (WFTV)", url: "https://livetv-fa.tubi.video/wftv/playlist.m3u8" },
    { name: "ABC 9 Tucson AZ (KGUN)", url: "https://livetv-fa.tubi.video/kgun/playlist.m3u8" },
    { name: "ABC News", url: "https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8" },
    { name: "ABC News Live 1", url: "https://abcnews-streams.akamaized.net/hls/live/2023560/abcnewshudson1/master_4000.m3u8" },
    { name: "ABC News Live 10", url: "https://abcnews-streams.akamaized.net/hls/live/2023569/abcnewshudson10/master_4000.m3u8" },
    { name: "ABC News Live 2", url: "https://abcnews-streams.akamaized.net/hls/live/2023561/abcnewshudson2/master_4000.m3u8" },
    { name: "ABC News Live 3", url: "https://abcnews-streams.akamaized.net/hls/live/2023562/abcnewshudson3/master_4000.m3u8" },
    { name: "ABC News Live 4", url: "https://abcnews-streams.akamaized.net/hls/live/2023563/abcnewshudson4/master_4000.m3u8" },
    { name: "ABC News Live 5", url: "https://abcnews-streams.akamaized.net/hls/live/2023564/abcnewshudson5/master_4000.m3u8" },
    { name: "ABC News Live 6", url: "https://abcnews-streams.akamaized.net/hls/live/2023565/abcnewshudson6/master_4000.m3u8" },
    { name: "ABC News Live 7", url: "https://abcnews-streams.akamaized.net/hls/live/2023566/abcnewshudson7/master_4000.m3u8" },
    { name: "ABC News Live 8", url: "https://abcnews-streams.akamaized.net/hls/live/2023567/abcnewshudson8/master_4000.m3u8" },
    { name: "ABC News Live 9", url: "https://abcnews-streams.akamaized.net/hls/live/2023568/abcnewshudson9/master_4000.m3u8" },
    { name: "ABC News New York NY (WABC-TV)", url: "https://content.uplynk.com/channel/ext/72750b711f704e4a94b5cfe6dc99f5e1/wabc_24x7_news.m3u8" },
    { name: "ABC Tallahassee", url: "https://content.uplynk.com/channel/c66d1d2d9e2c46cea1cf22a33f6ca488.m3u8" },
    { name: "ABC WWAY 3", url: "https://townnews.g-mana.live/media/027a05c7-43b6-49eb-ad10-a0c0f10a0754/main.m3u8" },
    { name: "ABN Afghanistan", url: "https://mediaserver.abnvideos.com/streams/abnafghanistan.m3u8" },
    { name: "ABN Africa", url: "https://mediaserver.abnvideos.com/streams/abnafrica.m3u8" },
    { name: "ABN Bible Movies", url: "https://mediaserver.abnvideos.com/streams/abnbiblemovies.m3u8" },
    { name: "ABN China", url: "https://mediaserver.abnvideos.com/streams/abnchina.m3u8" },
    { name: "ABN Freedom of Speech", url: "https://mediaserver.abnvideos.com/streams/freedom_of_speech.m3u8" },
    { name: "ABN I AM", url: "https://mediaserver.abnvideos.com/streams/i_am_.m3u8" },
    { name: "ABN Son of God", url: "https://mediaserver.abnvideos.com/streams/son_of_god_.m3u8" },
    { name: "ABN TV India", url: "https://mediaserver.abnvideos.com/streams/abntvindia.m3u8" },
    { name: "ABN Urdu", url: "https://mediaserver.abnvideos.com/streams/abnurdu.m3u8" },
    { name: "ACCDN", url: "https://livetv-fa.tubi.video/accdn2/playlist.m3u8" },
    { name: "ACL Cornhole TV", url: "https://1815337252.rsc.cdn77.org/HLS/CORNHOLETV.m3u8" },
    { name: "ACTV", url: "https://castus-vod-dev.s3.amazonaws.com/vod_clients/athens/live/ch2/video.m3u8" },
    { name: "AKC TV", url: "https://broadcast.blivenyc.com/speed/broadcast/22/desktop-playlist.m3u8" },
    { name: "AKC TV Meet The Breeds", url: "https://install.akctvcontrol.com/speed/broadcast/139/desktop-playlist.m3u8" },
    { name: "AKC TV Puppies 24/7", url: "https://install.akctvcontrol.com/speed/broadcast/140/desktop-playlist.m3u8" },
    { name: "AMG TV", url: "https://2-fss-2.streamhoster.com/pl_138/201660-1270634-1/playlist.m3u8" },
    { name: "ARTN TV", url: "https://streamer1.connectto.com/ARTN_mobile/index.m3u8" },
    { name: "ATVSat", url: "https://stream.atvsat.com/atvsatlive/smil:atvsatlive.smil/playlist.m3u8" },
    { name: "AWE", url: "https://a-cdn.klowdtv.com/live1/awe_720p/playlist.m3u8" },
    { name: "AWE Encore", url: "https://a-cdn.herringnetwork.com/affiliate/awee/playlist.m3u8" },
    { name: "Access Media Productions Channel", url: "https://dlttx48mxf9m3.cloudfront.net/vod_clients/amp/live/ch1/video.m3u8" },
    { name: "Access Media Productions Community Channel", url: "https://dlttx48mxf9m3.cloudfront.net/vod_clients/amp/live/ch2/video.m3u8" },
    { name: "Access Media Productions Marina TV", url: "https://dlttx48mxf9m3.cloudfront.net/vod_clients/amp/live/ch4/video.m3u8" },
    { name: "Access Media Productions Monterey Channel", url: "https://dlttx48mxf9m3.cloudfront.net/vod_clients/amp/live/ch3/video.m3u8" },
    { name: "Access Media Productions Peninsula Channel", url: "https://dlttx48mxf9m3.cloudfront.net/vod_clients/amp/live/ch5/video.m3u8" },
    { name: "Access Nashua", url: "https://livestream.telvue.com/nashuanh1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
    { name: "Access Tuolumne (Tuolumne County CA)", url: "https://reflect-tuolumne.cablecast.tv/live-3/live/stream-1/live.m3u8" },
    { name: "AccessVision Channel 16", url: "https://livestream.telvue.com/accvision1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
    { name: "AccessVision Channel 17", url: "https://livestream.telvue.com/accvision2/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
    { name: "AccuWeather Now", url: "https://amg00684-accuweather-accuweather-rokuus-0endj.amagi.tv/playlist.m3u8" },
    { name: "AfroLandTV", url: "https://alt-al.otteravision.com/alt/al/al.m3u8" },
    { name: "Aghapy Kids", url: "https://5b622f07944df.streamlock.net/aghapykids.tv/aghapykids2/playlist.m3u8" },
    { name: "Akaku 53 (Hawaii)", url: "https://castus-vod-dev.s3.amazonaws.com/vod_clients/akaku/live/ch1/video.m3u8" },
    { name: "Akaku 54 (Hawaii)", url: "https://castus-vod-dev.s3.amazonaws.com/vod_clients/akaku/live/ch2/video.m3u8" },
    { name: "Akaku 55 (Hawaii)", url: "https://castus-vod-dev.s3.amazonaws.com/vod_clients/akaku/live/ch3/video.m3u8" },
    { name: "Al Hayat TV", url: "https://cdn3.wowza.com/5/OE5HREpIcEkySlNT/alhayat-live/ngrp:livestream_all/playlist.m3u8" },
    { name: "Alfred Hitchcock Presents", url: "https://xumo-xumoent-ch825-ku23q.fast.nbcuni.com/live/master.m3u8" },
    { name: "Alhurra", url: "https://mbn-ingest-worldsafe.akamaized.net/hls/live/2038900/MBN_Alhurra_Worldsafe_HLS/master.m3u8" },
    { name: "Alien Nation", url: "https://linear-888.frequency.stream/dist/xumo/888/hls/master/playlist.m3u8" },
    { name: "Aliento Vision", url: "https://627bb251f23c7.streamlock.net:444/Alientoenvivo/Alientoenvivo/playlist.m3u8" },
    { name: "Alkarma TV Australia", url: "https://58cc65c534c67.streamlock.net/alkarmatv.com/alkarmaau.smil/playlist.m3u8" },
    { name: "Alkarma TV Family", url: "https://58cc65c534c67.streamlock.net/alkarmatv.com/alkarmaNA2.smil/playlist.m3u8" },
    { name: "Alkarma TV Middle East", url: "https://58cc65c534c67.streamlock.net/alkarmatv.com/alkarmame1.smil/playlist.m3u8" },
    { name: "Alkarma TV North America & Canada", url: "https://5aafcc5de91f1.streamlock.net/alkarmatv.com/alkarmana1.smil/playlist.m3u8" },
    { name: "Alkarma TV Praise", url: "https://58cc65c534c67.streamlock.net/alkarmatv.com/alkarmapa.smil/playlist.m3u8" },
    { name: "Alkarma TV Talmaza (Discipleship)", url: "https://58cc65c534c67.streamlock.net/alkarmatv.com/alkarmame2.smil/playlist.m3u8" },
    { name: "Alkarma TV Youth & English", url: "https://5aafcc5de91f1.streamlock.net/alkarmatv.com/alkarmaus.smil/playlist.m3u8" },
    { name: "Alkerazatv", url: "https://hwlive.streamingmediahosting.com/14221-live/0_ahgiewbd/playlist.m3u8" },
    { name: "Almagd TV Middle East", url: "https://597f64b67707a.streamlock.net/almagd.tv/almagd.smil/playlist.m3u8" },
    { name: "Almagd TV North America", url: "https://5aafcc5de91f1.streamlock.net/almagd.tv/almagd.smil/playlist.m3u8" },
    { name: "Alter Horror", url: "https://aegis-cloudfront-1.tubi.video/acac036c-181a-413a-a102-cd294c83320d/playlist.m3u8" },
    { name: "Always Funny Videos", url: "https://livetv-fa.tubi.video/afv/playlist.m3u8" },
    { name: "America's Voice", url: "https://content.uplynk.com/channel/26bd482ffe364a1282bc3df28bd3c21f.m3u8" },
    { name: "American Crimes", url: "https://xumo-xumoent-vc-113-at8kn.fast.nbcuni.com/live/master.m3u8" },
    { name: "American Ninja Warrior", url: "https://xumo-drct-ch812-n4996.fast.nbcuni.com/live/master.m3u8" },
    { name: "American Pickers Channel", url: "https://amg00979-amg00979c1-firetv-us-3622.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "True Crime Network+", url: "https://amg00979-amg00979c1-firetv-us-3622.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "True Crime Now", url: "https://amg00376-magellan-amg00376c12-samsung-nz-1727.playouts.now.amagi.tv/playlist/amg00376-magellantv-truecrimenowaunzin-samsungnz/playlist.m3u8" },
    { name: "True History", url: "https://linear-188.frequency.stream/dist/glewedtv/188/hls/master/playlist.m3u8" },
    { name: "True History Channel", url: "https://linear-188.frequency.stream/dist/xumo/188/hls/master/playlist.m3u8" },
    { name: "Tubi Originals", url: "https://livetv-fa.tubi.video/tubi-originals/index.m3u8" },
    { name: "UCTV University of California", url: "https://59e8e1c60a2b2.streamlock.net/509/509.stream/playlist.m3u8" },
    { name: "UFC", url: "https://linear-893.frequency.stream/dist/xumo/893/hls/master/playlist.m3u8" },
    { name: "UN Web TV", url: "https://cdnapi.kaltura.com/p/2503451/sp/250345100/playManifest/entryId/1_gb6tjmle/protocol/https/format/applehttp/a.m3u8" },
    { name: "USA Today News", url: "https://usatodaynews-xumo.amagi.tv/playlist.m3u8" },
    { name: "Universal Action", url: "https://xumo-xumoent-ch828-w6val.fast.nbcuni.com/live/master.m3u8" },
    { name: "Universal Crime", url: "https://xumo-xumoent-vc-107-xmuvk.fast.nbcuni.com/live/master.m3u8" },
    { name: "Universal Monsters", url: "https://xumo-xumoent-ch824-d4q5c.fast.nbcuni.com/live/master.m3u8" },
    { name: "Universal Westerns", url: "https://xumo-xumoent-ch834-iwtka.fast.nbcuni.com/live/master.m3u8" },
    { name: "Unsolved Mysteries", url: "https://livetv-fa.tubi.video/unsolved-mysteries/index.m3u8" },
    { name: "Up TV", url: "https://fl1.moveonjoy.com/Up_Tv/index.m3u8" },
    { name: "VBS TV", url: "https://tgn.bozztv.com/vbstvcdn/vbstv/ngrp:vbstv_all/playlist.m3u8" },
    { name: "VOA Persian", url: "https://voa-ingest.akamaized.net/hls/live/2033876/tvmc07/playlist.m3u8" },
    { name: "VOA TV Africa", url: "https://voa-ingest.akamaized.net/hls/live/2033874/tvmc06/playlist.m3u8" },
    { name: "VSiN", url: "https://vsin-sgrewind.streamguys1.com/scte/live-2k/playlist.m3u8" },
    { name: "VTN Victory Television Network", url: "https://jk3lzkn4lw79-hls-live.5centscdn.com/VTN2/bcaafe9ad8d42834b08e762ac58596b8.sdp/playlist.m3u8" },
    { name: "Vacaville Channel 26 (Vacaville CA)", url: "https://cdn3.wowza.com/5/RXJNMFI3VlVkOEFP/vacaville/G0228_002/playlist.m3u8" },
    { name: "Vallenato Internacional", url: "https://59a564764e2b6.streamlock.net/vallenato/vallenatom/playlist.m3u8" },
    { name: "Velayat TV", url: "https://nl.livekadeh.com/hls2/velayattv.m3u8" },
    { name: "Vice News", url: "https://vicetv-vicefast2-firetv.amagi.tv/playlist.m3u8" },
    { name: "Vice TV", url: "https://aegis-cloudfront-1.tubi.video/afa9e2ab-abda-47c0-9fd5-48c9641aaa9e/playlist.m3u8" },
    { name: "Village of Hastings-On-Hudson NY (WHOH-TV)", url: "https://stream.swagit.com/live-edge/hastingsonhudsonny/smil:std-4x3-1-a/playlist.m3u8" },
    { name: "Vision Global TV", url: "https://vdopanel.jlahozconsulting.com:3407/hybrid/play.m3u8" },
    { name: "W14DK-D 14.1 TV Delmarva", url: "https://2-fss-2.streamhoster.com/pl_118/amlst:204972-1949480/playlist.m3u8" },
    { name: "W14DK-D 14.2 NEWSNET", url: "https://2-fss-2.streamhoster.com/pl_118/204972-1954106-1/playlist.m3u8" },
    { name: "WABC-DT1", url: "https://fl25.moveonjoy.com/ABC_EAST/index.m3u8" },
    { name: "WBTV At the Movies", url: "https://livetv-fa.tubi.video/wbd-at-the-movies/playlist.m3u8" },
    { name: "WBTV Chasing Criminals", url: "https://livetv-fa.tubi.video/wbd-chasing-criminals/playlist.m3u8" },
    { name: "WBTV Classic Cinema", url: "https://livetv-fa.tubi.video/wbd-classic-cinema/playlist.m3u8" },
    { name: "WBTV Crime scenes", url: "https://livetv-fa.tubi.video/wbd-crime-scenes/playlist.m3u8" },
    { name: "WBTV Family Faves", url: "https://livetv-fa.tubi.video/wbd-all-together-now/playlist.m3u8" },
    { name: "WBTV Family Unscripted", url: "https://livetv-fa.tubi.video/wbd-family-rules/playlist.m3u8" },
    { name: "WBTV Generation Drama", url: "https://livetv-fa.tubi.video/wbd-generation-drama/playlist.m3u8" },
    { name: "WBTV Ghosts are Real", url: "https://livetv-fa.tubi.video/wbd-supernatural/playlist.m3u8" },
    { name: "WBTV HBO Boxing", url: "https://livetv-fa.tubi.video/wbd-hbo-boxing/playlist.m3u8" },
    { name: "WBTV How To", url: "https://livetv-fa.tubi.video/wbd-how-to/playlist.m3u8" },
    { name: "WBTV In The Garage", url: "https://livetv-fa.tubi.video/wbd-in-the-garage/playlist.m3u8" },
    { name: "WBTV Living With Evil", url: "https://livetv-fa.tubi.video/wbd-living-with-evil/playlist.m3u8" },
    { name: "WBTV Love & Desire", url: "https://livetv-fa.tubi.video/wbd-keeping-it-real/playlist.m3u8" },
    { name: "WBTV Love and Marriage", url: "https://livetv-fa.tubi.video/wbd-love-marriage/playlist.m3u8" },
    { name: "WBTV Mysterious Worlds", url: "https://livetv-fa.tubi.video/wbd-mysteries/playlist.m3u8" },
    { name: "WBTV Nikita", url: "https://livetv-fa.tubi.video/wbd-nikita/playlist.m3u8" },
    { name: "WBTV On The Telly", url: "https://livetv-fa.tubi.video/wbd-on-the-telly/playlist.m3u8" },
    { name: "WBTV Paws and Claws", url: "https://livetv-fa.tubi.video/wbd-paws-claws/playlist.m3u8" },
    { name: "WBTV Sweet Escapes", url: "https://livetv-fa.tubi.video/wbd-sweet-escapes/playlist.m3u8" },
    { name: "WBTV The FBI", url: "https://livetv-fa.tubi.video/wbd-the-fbi/playlist.m3u8" },
    { name: "WBTV Travel and Adventure", url: "https://livetv-fa.tubi.video/wbd-travel-and-adventure/playlist.m3u8" },
    { name: "WBTV Unique Lives", url: "https://livetv-fa.tubi.video/wbd-slice-life/playlist.m3u8" },
    { name: "WBTV Watchlist", url: "https://livetv-fa.tubi.video/wbd-watch-list/playlist.m3u8" },
    { name: "WBTV Welcome Home", url: "https://livetv-fa.tubi.video/wbd-welcome-home/playlist.m3u8" },
    { name: "WCBI (Columbus MI)", url: "https://townnews.g-mana.live/media/4efc62fa-ad0b-445c-a839-4d1e7636988e/main.m3u8" },
    { name: "WCBS-DT1", url: "https://fl1.moveonjoy.com/CBSEAST/index.m3u8" },
    { name: "WCOT 13 (Tallahassee FL)", url: "https://stream.talgov.net/WCOT/smil:WCOT.smil/playlist.m3u8" },
    { name: "WDEF-TV News Chattanooga TN", url: "https://townnews.g-mana.live/media/a54a6409-5e91-46f0-9fee-06904c1fd094/main.m3u8" },
    { name: "WEDQ-DT4", url: "https://wedqdt4.lls.pbs.org/wedqdt4-hls.m3u8" },
    { name: "WFLX-DT1", url: "https://fl1.moveonjoy.com/FL_West_Palm_Beach_FOX/index.m3u8" },
    { name: "WFMZ Dorney Park Camera", url: "https://cdn.jaybirdtv.com/wfmz/5/live/master.m3u8" },
    { name: "WFMZ PennST camera", url: "https://cdn.jaybirdtv.com/wfmz/6/live/master.m3u8" },
    { name: "WFMZ Traffic", url: "https://cdn.jaybirdtv.com/wfmz/channel/7/master.m3u8" },
    { name: "WFTT-DT1", url: "https://streaming-live-fcdn.api.prd.univisionnow.com/wfut/wfut.isml/hls/wfut.m3u8" },
    { name: "WFTX News Fort Myers FL", url: "https://content.uplynk.com/channel/8975f81e6efd4e609873c3e8e25c7756.m3u8" },
    { name: "WGTV-DT3", url: "https://wgtvdt3.lls.pbs.org/wgtvdt3-cmaf-hls.m3u8" },
    { name: "WHBQ-DT1", url: "https://livetv-fa.tubi.video/whbq3/playlist.m3u8" },
    { name: "WHIO-DT1", url: "https://livetv-fa.tubi.video/whio2/playlist.m3u8" },
    { name: "WHPS Detroit", url: "https://f-tx-edge-87.christianworldmedia.com/313watkins/mp4:313watkins/playlist.m3u8" },
    { name: "WITN 22 (Wilmington DE)", url: "https://witn.cablecast.tv/live-4/live/live.m3u8" },
    { name: "WKCF-DT1", url: "https://fl1.moveonjoy.com/CW_ORLANDO/index.m3u8" },
    { name: "WKCF-DT2", url: "https://dvrfl03.bozztv.com/hondu-lxnews/index.m3u8" },
    { name: "WKMG-DT1", url: "https://dvrfl03.bozztv.com/hondu-cbsorlando/index.m3u8" },
    { name: "WKOH-DT4", url: "https://dvrfl03.bozztv.com/hondu/hondu-pbs-kids/index.m3u8" },
    { name: "WLMB", url: "https://rpn.bozztv.com/wlmb/wlmb/wlmb/index.m3u8" },
    { name: "WLS ABC 7 News (Chicago IL)", url: "https://content.uplynk.com/channel/ext/aac37e2c66614e699fb189ab391084ff/wls_24x7_news.m3u8" },
    { name: "WLVT-DT1", url: "https://dvrfl03.bozztv.com/hondu/hondu-gbp-pbs/index.m3u8" },
    { name: "WMGT-TV News (Macon GA)", url: "https://townnews.g-mana.live/media/e6909128-cd42-4690-8340-4b8a49455666/main.m3u8" },
    { name: "WMOR-TV News Lakeland FL", url: "https://livetv-fa.tubi.video/wmor/playlist.m3u8" },
    { name: "WMPT-DT2 (PBS Create)", url: "https://2-fss-1.streamhoster.com/pl_122/amlst:201814-2122456/playlist.m3u8" },
    { name: "WNBC-DT1", url: "https://e1.thetvapp.to/hls/WNBCDT1/tracks-v1a1/mono.m3u8" },
    { name: "WOFL-DT1", url: "https://livetv-fa.tubi.video/wofl/index.m3u8" },
    { name: "WPEC-DT1", url: "https://fl1.moveonjoy.com/FL_West_Palm_Beach_CBS/index.m3u8" },
    { name: "WPTV News West Palm Beach FL", url: "https://content.uplynk.com/channel/b02350ef854c4eef8358eead1f59a5cc.m3u8" },
    { name: "WPVI ABC 6 News (Philadelphia PA)", url: "https://content.uplynk.com/channel/ext/10b98e7c615f43a98b180d51797e74aa/wpvi_24x7_news.m3u8" },
    { name: "WPXI-DT1", url: "https://livetv-fa.tubi.video/wpxi2/playlist.m3u8" },
    { name: "WSB-DT1", url: "https://livetv-fa.tubi.video/wsb2/playlist.m3u8" },
    { name: "WSOC-DT1", url: "https://aegis-cloudfront-1.tubi.video/d864a20b-85bb-41bc-8fbe-6c9d8a88a32d/playlist.m3u8" },
    { name: "WTMO-CD1", url: "https://dvrfl03.bozztv.com/hondu-telexitos/index.m3u8" },
    { name: "WTOG-DT1", url: "https://fl1.moveonjoy.com/FL_Tampa_CW44/index.m3u8" },
    { name: "WTVD ABC 11 News (Raleigh-Durham NC)", url: "https://content.uplynk.com/channel/ext/f05837c508c44712aa7129d531f7dbe6/wtvd_24x7_news.m3u8" },
    { name: "WTVQ ABC 36 News (Lexington KY)", url: "https://townnews.g-mana.live/media/14d1fd2c-0548-4803-80ad-6657831a7981/main.m3u8" },
    { name: "WUPA-DT1", url: "https://dvrfl03.bozztv.com/hondu/hondu-ovair1-cwhd/index.m3u8" },
    { name: "WVCU-LP Concord University Radio The Cure 97.7", url: "https://video1.getstreamhosting.com:1936/8152/8152/playlist.m3u8" },
    { name: "WWON TV CH 48", url: "https://tv2.fastcast4u.com:3943/stream/play.m3u8" },
    { name: "WXTV-DT1", url: "https://streaming-live-fcdn.api.prd.univisionnow.com/wxtv/wxtv.isml/hls/wxtv.m3u8" },
    { name: "WXXV-TV News (Biloxi MS)", url: "https://townnews.g-mana.live/media/c8c354e0-672f-4368-a17d-a862ee98af4a/main.m3u8" },
    { name: "Wanted: Dead or Alive", url: "https://livetv-fa.tubi.video/wanted-dead-or-alive2/playlist.m3u8" },
    { name: "Waypoint TV", url: "https://livetv-fa.tubi.video/waypoint/playlist.m3u8" },
    { name: "West Hollywood WeHoTV (West Hollywood CA)", url: "https://cdn3.wowza.com/5/M0lyamVmM2JWcjhQ/weho/G0161_004/playlist.m3u8" },
    { name: "White Plains Community Media", url: "https://stream.swagit.com/live-edge/whiteplainsny/smil:std-4x3-1-b/playlist.m3u8" },
    { name: "Whittier CityTV (Whittier CA)", url: "https://whittier.cablecast.tv/live/stream-1/live.m3u8" },
    { name: "Wild West TV", url: "https://linear-799.frequency.stream/dist/xumo/799/hls/master/playlist.m3u8" },
    { name: "Willow", url: "https://fl1.moveonjoy.com/WILLOW_CRICKET/index.m3u8" },
    { name: "Willow Sports", url: "https://amg01269-amg01269c1-firetv-us-5377.playouts.now.amagi.tv/playlist.m3u8" },
    { name: "Wine Watches & Whiskey", url: "https://www-on-stirr.b-cdn.net/Wine-Watches-and-Whiskey/playlist.m3u8" },
    { name: "Wipeout Xtra", url: "https://livetv-fa.tubi.video/wipeout-xtra/playlist.m3u8" },
    { name: "Wired2Fish", url: "https://wire2fish-klowdtv.amagi.tv/playlist.m3u8" },
    { name: "Wolcott Governmental TV (Wolcott CT)", url: "https://5a5c57d042315.streamlock.net/live11704001/ngrp:government_all/playlist.m3u8" },
    { name: "Women's Sports Network", url: "https://livetv-fa.tubi.video/fast-studios-womens-sports/playlist.m3u8" },
    { name: "Womens Sports Network Canada", url: "https://livetv-fa.tubi.video/womens-sports-network-canada/playlist.m3u8" },
    { name: "World Channel", url: "https://world.lls.pbs.org/index.m3u8" },
    { name: "World Harvest TV", url: "https://597865f6e4114.streamlock.net/live/leseaorigin.stream/playlist.m3u8" },
    { name: "World Poker Tour", url: "https://amg00218-wptenterprisesi-worldpokertour-xumo-us.amagi.tv/playlist.m3u8" },
    { name: "Xplore", url: "https://aegis-cloudfront-1.tubi.video/4cfc30dc-1431-46b6-aea7-89a2e7d35823/playlist.m3u8" },
    { name: "YTA TV", url: "https://yta.unitedteleports.tv/hls/YTA.m3u8" },
    { name: "Yahoo! Finance", url: "https://d1ewctnvcwvvvu.cloudfront.net/playlist.m3u8" },
    { name: "YouDotGov", url: "https://reflect-communitytv.cablecast.tv/live-3/live/stream-1/live.m3u8" },
    { name: "Young Hollywood", url: "https://younghollywood-rakuten-samsung.amagi.tv/playlist.m3u8" },
    { name: "Yu-Gi-Oh! en espanol", url: "https://amg01796-amg01796c18-rakuten-es-7491.playouts.now.amagi.tv/playlist/amg01796-fastmediafast-yugiohees-rakutenes/playlist.m3u8" },
    { name: "Yuma AZ CH 72", url: "https://livestream.telvue.com/yumaaz1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
    { name: "Yuma AZ CH 73", url: "https://livestream.telvue.com/yumaaz2/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
    { name: "Zarin TV", url: "https://fl1002.bozztv.com/gf-zarintv/index.m3u8" },
    { name: "bon appétit", url: "https://bonappetit-samsung.amagi.tv/playlist.m3u8" },
    { name: "pocket.watch", url: "https://pocketwatch-xumo.amagi.tv/playlist.m3u8" },
    { name: "theDove TV", url: "https://thedovetv.bozztv.com/thedovetv/thedovetv/index.m3u8" },
  ],
}

channelsByCountry["United States of America"] = channelsByCountry["United States"];

/**
 * Fetches channels available for a specific country
 */
export async function getChannelsByCountry(country: string): Promise<IPTVChannel[]> {
  await new Promise((resolve) => setTimeout(resolve, 300))
  const channels = channelsByCountry[country] || []
  return channels.map((ch) => ({
    ...ch,
    url: normalizeYouTubeUrl(ch.url),
  }))
}